import type { Nux } from "../types";
import { populateKnobs } from "../utils/effectHelper";

const populateAmpKnobs = (knobData: Nux.KnobEntry[] = PRIMARY_VARIANT) => {
  return populateKnobs(knobData, 24);
};

const PRIMARY_VARIANT: Nux.KnobEntry[] = [
  ["gain", "GAIN"],
  ["master", "MASTER"],
  ["bass", "BASS"],
  ["middle", "MIDDLE"],
  ["treble", "TREBLE"],
  ["presence", "PRESENCE"],
  ["bias", "BIAS LEVEL"],
  ["level", "LEVEL"],
];

const PRIMARY_BRIGHT_VARIANT: Nux.KnobEntry[] = [
  ["gain", "GAIN"],
  ["master", "MASTER"],
  ["bass", "BASS"],
  ["middle", "MIDDLE"],
  ["treble", "TREBLE"],
  ["bright", "", [0, 1]],
  ["bias", "BIAS LEVEL"],
  ["level", "LEVEL"],
];
const PRIMARY_BRIGHT_VARIANT_WITHOUT_BIAS: Nux.KnobEntry[] = [
  ["gain", "GAIN"],
  ["master", "MASTER"],
  ["bass", "BASS"],
  ["middle", "MIDDLE"],
  ["treble", "TREBLE"],
  ["bright", "", [0, 1]],
  ["level", "LEVEL"],
];
const AGL_VARIANT: Nux.KnobEntry[] = [
  ["gain", "GAIN"],
  ["master", "MASTER"],
  ["bass", "BASS"],
  ["middle", "MIDDLE"],
  ["mfreq", "M. FREQUENCY"],
  ["treble", "TREBLE"],
  ["level", "LEVEL"],
];

const PRIMARY_VARIANT_WITHOUT_BIAS: Nux.KnobEntry[] = [
  ["gain", "GAIN"],
  ["master", "MASTER"],
  ["bass", "BASS"],
  ["middle", "MIDDLE"],
  ["treble", "TREBLE"],
  ["presence", "PRESENCE"],
  ["level", "LEVEL"],
];

const SECOND_VARIANT: Nux.KnobEntry[] = [
  ["gain", "GAIN"],
  ["master", "MASTER"],
  ["cut", "CUT"],
  ["bass", "BASS"],
  ["middle", "MIDDLE"],
  ["treble", "TREBLE"],
  ["level", "LEVEL"],
];

const SECOND_VARIANT_WITHOUT_MIDDLE: Nux.KnobEntry[] = [
  ["gain", "GAIN"],
  ["master", "MASTER"],
  ["cut", "CUT"],
  ["bass", "BASS"],
  ["middle", "MIDDLE"],
  ["treble", "TREBLE"],
  ["level", "LEVEL"],
];

const DGLASS_VARIANT: Nux.KnobEntry[] = [
  ["master", "MASTER"],
  ["bass", "BASS"],
  ["1hz", "Hertz 1", [0, 2]],
  ["lomids", "LO MIDS"],
  ["himids", "HI MIDS"],
  ["2hz", "Hertz 2", [0, 2]],
  ["treble", "TREBLE"],
  ["level", "LEVEL"],
];

const STARLIFT_VARIANT: Nux.KnobEntry[] = [
  ["bass", "BASS"],
  ["mid", "MID"],
  ["midfreq", "MID FREQ"],
  ["treble", "TREBLE"],
  ["contour", "CONTOUR", [0, 2]],
  ["volume", "VOLUME"],
  ["level", "LEVEL"],
];

const PRINCETON_VARIANT: Nux.KnobEntry[] = [
  ["volume", "VOLUME"],
  ["treble", "TREBLE"],
  ["bass", "BASS"],
  ["bias", "BIAS LEVEL"],
  ["level", "LEVEL"],
];

const TWEEDY_VARIANT: Nux.KnobEntry[] = [
  ["gain", "GAIN"],
  ["tone", "TONE"],
  ["master", "MASTER"],
  ["level", "LEVEL"],
];

export default {
  amp: {
    category: "amp",
    options: [
      {
        id: "JAZZ_CLEAN",
        title: "Jazz Clean",
        onByte: "01",
        offByte: "65",
        dominantColor: "#90A4AE",
        ...populateAmpKnobs(PRIMARY_BRIGHT_VARIANT_WITHOUT_BIAS),
      },
      {
        id: "DELUXE_RVB",
        title: "Deluxe Reverb",
        onByte: "02",
        offByte: "42",
        dominantColor: "#004D40",
        ...populateAmpKnobs(),
      },
      {
        id: "BASSMATE",
        title: "Bassmate",
        onByte: "03",
        offByte: "43",
        dominantColor: "#FF9800",
        ...populateAmpKnobs(),
      },
      {
        id: "TWEEDY",
        title: "Tweedy",
        onByte: "04",
        offByte: "44",
        dominantColor: "#FFC107",
        ...populateAmpKnobs(TWEEDY_VARIANT),
      },
      {
        id: "TWIN_RVB",
        title: "Twin Reverb",
        onByte: "05",
        offByte: "45",
        dominantColor: "#66BB6A",
        ...populateAmpKnobs(PRIMARY_BRIGHT_VARIANT),
      },
      {
        id: "HIWIRE",
        title: "Hiwire",
        onByte: "06",
        offByte: "46",
        dominantColor: "#BDBDBD",
        ...populateAmpKnobs(),
      },
      {
        id: "CALI_CRUNCH",
        title: "Cali Crunch",
        onByte: "07",
        offByte: "47",
        dominantColor: "#FFECB3",
        ...populateAmpKnobs(),
      },
      {
        id: "CLASS_A15",
        title: "Class A15",
        onByte: "08",
        offByte: "48",
        dominantColor: "#BCAAA4",
        ...populateAmpKnobs(SECOND_VARIANT_WITHOUT_MIDDLE),
      },
      {
        id: "CLASS_A30",
        title: "Class A30",
        onByte: "09",
        offByte: "49",
        dominantColor: "#E91E63",
        ...populateAmpKnobs(SECOND_VARIANT_WITHOUT_MIDDLE),
      },
      {
        id: "PLEXI_100",
        title: "Plexi 100",
        onByte: "0A",
        offByte: "4A",
        dominantColor: "#FFA726",
        ...populateAmpKnobs(),
      },
      {
        id: "PLEXI_45",
        title: "Plexi 45",
        onByte: "0B",
        offByte: "4B",
        dominantColor: "#FFCA28",
        ...populateAmpKnobs(),
      },
      {
        id: "BRIT_800",
        title: "Brit 800",
        onByte: "0C",
        offByte: "4C",
        dominantColor: "#FFCC80",
        ...populateAmpKnobs(),
      },
      {
        id: "1987_X_50",
        title: "1987 X 50",
        onByte: "0D",
        offByte: "4D",
        dominantColor: "#FFE0B2",
        ...populateAmpKnobs(),
      },
      {
        id: "SLO_100",
        title: "SLO 100",
        onByte: "0E",
        offByte: "4E",
        dominantColor: "#B2DFDB",
        ...populateAmpKnobs(),
      },
      {
        id: "FIREMAN_HBE",
        title: "Fireman HBE",
        onByte: "0F",
        offByte: "4F",
        dominantColor: "#9E9D24",
        ...populateAmpKnobs(),
      },
      {
        id: "DUAL_RECT",
        title: "Dual Rect",
        onByte: "10",
        offByte: "50",
        dominantColor: "#000000",
        ...populateAmpKnobs(),
      },
      {
        id: "DIE_VH4",
        title: "Die VH4",
        onByte: "11",
        offByte: "51",
        dominantColor: "#F5F5F5",
        ...populateAmpKnobs(),
      },
      {
        id: "VIBRO_KING",
        title: "Vibro King",
        onByte: "12",
        offByte: "52",
        dominantColor: "#C6BE7E",
        ...populateAmpKnobs(),
      },
      {
        id: "BUDDA",
        title: "Budda",
        onByte: "13",
        offByte: "53",
        dominantColor: "#CE93D8",
        ...populateAmpKnobs(SECOND_VARIANT),
      },
      {
        id: "MR_Z_38",
        title: "Mr. Z 38",
        onByte: "14",
        offByte: "54",
        dominantColor: "#E57373",
        ...populateAmpKnobs(SECOND_VARIANT),
      },
      {
        id: "SUPER_RVB",
        title: "Super RVB",
        onByte: "15",
        offByte: "55",
        dominantColor: "#004D40",
        ...populateAmpKnobs(PRIMARY_BRIGHT_VARIANT),
      },
      {
        id: "BRIT_BLUES",
        title: "Brit Blues",
        onByte: "16",
        offByte: "56",
        dominantColor: "#FFE082",
        ...populateAmpKnobs(),
      },
      {
        id: "MATCH",
        title: "Match",
        onByte: "17",
        offByte: "57",
        dominantColor: "#000000",
        ...populateAmpKnobs(SECOND_VARIANT_WITHOUT_MIDDLE),
      },
      {
        id: "BRIT_2000",
        title: "Brit 2000",
        onByte: "18",
        offByte: "58",
        dominantColor: "#FFE060",
        ...populateAmpKnobs(),
      },
      {
        id: "UBER",
        title: "Uber",
        onByte: "19",
        offByte: "59",
        dominantColor: "#455A64",
        ...populateAmpKnobs(),
      },
      {
        id: "AGL",
        title: "AGL",
        onByte: "1A",
        offByte: "5A",
        dominantColor: "#BDBDBD",
        ...populateAmpKnobs(AGL_VARIANT),
      },
      {
        id: "BASSGUY",
        title: "Bassguy",
        onByte: "1B",
        offByte: "5B",
        dominantColor: "#CFD8DC",
        ...populateAmpKnobs(PRIMARY_VARIANT_WITHOUT_BIAS),
      },
      {
        id: "MLD",
        title: "MLD",
        onByte: "1C",
        offByte: "5C",
        dominantColor: "#1565C0",
        ...populateAmpKnobs(PRIMARY_VARIANT_WITHOUT_BIAS),
      },
      {
        id: "OPTIMA_AIR",
        title: "Optima Air",
        onByte: "1D",
        offByte: "5D",
        dominantColor: "#FFB830",
        ...populateAmpKnobs(PRIMARY_VARIANT_WITHOUT_BIAS),
      },
      {
        id: "STAGEMAN",
        title: "Stageman",
        onByte: "1E",
        offByte: "5E",
        dominantColor: "#FFF59D",
        ...populateAmpKnobs(PRIMARY_VARIANT_WITHOUT_BIAS),
      },
      {
        id: "DGLASS",
        title: "Dglass",
        onByte: "1F",
        offByte: "5F",
        dominantColor: "#FFF59D",
        ...populateAmpKnobs(DGLASS_VARIANT),
      },
      {
        id: "STARLIFT",
        title: "Starlift",
        onByte: "20",
        offByte: "60",
        dominantColor: "#42A5F5",
        ...populateAmpKnobs(STARLIFT_VARIANT),
      },
      {
        id: "VIVO",
        title: "Vivo",
        onByte: "21",
        offByte: "61",
        dominantColor: "#EEEEEE",
        ...populateAmpKnobs(),
      },
      {
        id: "F_PRINCETON",
        title: "F Princeton",
        onByte: "22",
        offByte: "62",
        dominantColor: "#00796B",
        ...populateAmpKnobs(PRINCETON_VARIANT),
      },
      {
        id: "LONESTAR",
        title: "Lonestar",
        onByte: "23",
        offByte: "63",
        dominantColor: "#FFE082",
        ...populateAmpKnobs(),
      },
    ],
  },
};
